# Generated by Django 6.0.3 on 2026-03-04 00:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officer',
            name='department',
        ),
        migrations.AddField(
            model_name='defendant',
            name='alt_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='defendant',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='defendant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='defendant',
            name='email_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='defendant',
            name='physical_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='defendant',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='defendant',
            name='preferred_method',
            field=models.CharField(choices=[('all', 'All'), ('email', 'Email'), ('sms', 'SMS')], default='all', max_length=20),
        ),
        migrations.AddField(
            model_name='defendant',
            name='sms_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='defendant',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defendant_info', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='officermanagement',
            name='action',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='officermanagement',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='officermanagement',
            name='badge',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='officermanagement',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='officermanagement',
            name='role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userrole',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='officermanagement',
            name='officer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='management', to='app.officer'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_tickets', to='app.officer'),
        ),
        migrations.CreateModel(
            name='Nampol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.officer')),
            ],
        ),
    ]
